In [1]:
pwd

'C:\\Users\\ayofa\\SGA08_DATSCI'

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 5037-8331

 Directory of C:\Users\ayofa\SGA08_DATSCI

24/06/2020  12:57 PM    <DIR>          .
24/06/2020  12:57 PM    <DIR>          ..
23/06/2020  12:39 AM    <DIR>          .git
24/06/2020  12:57 PM    <DIR>          .ipynb_checkpoints
23/06/2020  12:38 AM               163 README.md
23/06/2020  03:14 PM             3,451 Untitled.ipynb
24/06/2020  12:57 PM                72 Untitled1.ipynb
               3 File(s)          3,686 bytes
               4 Dir(s)  122,242,260,992 bytes free


 Volume in drive C is Windows
 Volume Serial Number is 5037-8331

 Directory of C:\Users\ayofa\SGA08_DATSCI

24/06/2020  12:57 PM    <DIR>          .
24/06/2020  12:57 PM    <DIR>          ..
23/06/2020  12:39 AM    <DIR>          .git
24/06/2020  12:57 PM    <DIR>          .ipynb_checkpoints
24/06/2020  12:54 PM               153 interact_list.csv
23/06/2020  12:38 AM               163 README.md
23/06/2020  03:14 PM             3,451 Untitled.ipynb
24/06/2020  12:57 PM                72 Untitled1.ipynb
               4 File(s)          3,839 bytes
               4 Dir(s)  122,241,622,016 bytes free


In [4]:
#import pandas
import pandas as pd

In [7]:
#importing data
human = pd.read_csv ('interact_list.csv')

In [8]:
print(human)

   gender  age  salary
0    male   62    2900
1    male   46    4100
2  female   55    3900
3    male   49    5200
4  female   31    7000
5  female   48    4100
6  female   51    3800
7    male   56    3300
8    male   57    3000


In [9]:
#human info
human.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   gender  9 non-null      object
 1   age     9 non-null      int64 
 2   salary  9 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 344.0+ bytes


In [10]:
print(human.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   gender  9 non-null      object
 1   age     9 non-null      int64 
 2   salary  9 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 344.0+ bytes
None


In [15]:
human.columns()

TypeError: 'Index' object is not callable

In [14]:
print(human.columns)

Index(['gender', 'age', 'salary'], dtype='object')


In [19]:
print(human.dtypes)

gender    object
age        int64
salary     int64
dtype: object


In [20]:
#importing numpy for array creation
import numpy as np

In [21]:
human.age

0    62
1    46
2    55
3    49
4    31
5    48
6    51
7    56
8    57
Name: age, dtype: int64

In [22]:
#changing some data variables from list to array
np_human_age = np.array(human.age)
np_human_salary = np.array(human.salary)

In [23]:
print(np_human_age)

[62 46 55 49 31 48 51 56 57]


In [42]:
np_human = np.array(human)

In [45]:
np_human[1] 

array(['male', 46, 4100], dtype=object)

In [46]:
np_human[2]

array(['female', 55, 3900], dtype=object)

In [47]:
np_human[0]

array(['male', 62, 2900], dtype=object)

In [48]:
np_human[7]

array(['male', 56, 3300], dtype=object)

In [24]:
np_human_age >= 48

array([ True, False,  True,  True, False,  True,  True,  True,  True])

In [28]:
np_human_age[np_human_age >= 48]

array([62, 55, 49, 48, 51, 56, 57], dtype=int64)

In [29]:
print(human.age)

0    62
1    46
2    55
3    49
4    31
5    48
6    51
7    56
8    57
Name: age, dtype: int64


In [41]:
#details about the dataset 'interact_list'
stats = human.describe()

In [37]:
print(stats)

             age       salary
count   9.000000     9.000000
mean   50.555556  4144.444444
std     8.903807  1275.843947
min    31.000000  2900.000000
25%    48.000000  3300.000000
50%    51.000000  3900.000000
75%    56.000000  4100.000000
max    62.000000  7000.000000


In [73]:
#creating a dictionary for arrays above
dict = {'first': np_human[1], 'second': np_human[0], 'third': np_human[7], 'fourth': np_human[2], 'fifth': np_human[4]}



In [74]:
#testing dictionary
print (dict['first'])

['male' 46 4100]


In [75]:
#testing dictionary
print (dict['fifth'])

['female' 31 7000]


In [76]:
print(dict)

{'first': array(['male', 46, 4100], dtype=object), 'second': array(['male', 62, 2900], dtype=object), 'third': array(['male', 56, 3300], dtype=object), 'fourth': array(['female', 55, 3900], dtype=object), 'fifth': array(['female', 31, 7000], dtype=object)}


In [77]:
dict

{'first': array(['male', 46, 4100], dtype=object),
 'second': array(['male', 62, 2900], dtype=object),
 'third': array(['male', 56, 3300], dtype=object),
 'fourth': array(['female', 55, 3900], dtype=object),
 'fifth': array(['female', 31, 7000], dtype=object)}

In [97]:
import csv
dict = {'first': np_human[1], 'second': np_human[0], 'third': np_human[7],
        'fourth': np_human[2], 'fifth': np_human[4]}
keys = dict[0].keys()
with open('people.csv', 'wb') as output_file:
    dict_writer = csv.DictWriter(output_file, keys)
    dict_writer.writeheader()
    dict_writer.writerows(dict)

KeyError: 0

In [101]:
from pandas import DataFrame

In [108]:
dict = {'first': np_human[1], 'second': np_human[0], 'third': np_human[7], 'fourth': np_human[2], 'fifth': np_human[4]}
df = DataFrame(list(dict.items()),columns = ['Cardinal_Numbers', 'Gender_Age_Salary'])

In [109]:
print (df)

  Cardinal_Numbers   Gender_Age_Salary
0            first    [male, 46, 4100]
1           second    [male, 62, 2900]
2            third    [male, 56, 3300]
3           fourth  [female, 55, 3900]
4            fifth  [female, 31, 7000]


In [110]:
df.to_csv('new_interact.csv')